
#baseURL = 'https://example.org/'
#baseURL = 'https://kk-karl.github.io/'
baseURL = 'https://kk-karl.github.io/booklog'
#baseURL = 'https://kk-karl.github.io'
#languageCode = 'en-us'
languageCode = 'zh-cn'
title = 'mybooklog'


copyright = 'Â© 2024-2099 mybooklog'
disqusShortname = '111222'
theme = 'github-style'
#theme = 'hugo-vitae'
relativeURLs = true
relURL = 'https://kk-karl.github.io/booklog'
#uglyURLs = true
buildfuture = true
pygmentsUseClasses = true
pygmentsCodeFences = true
#googleAnalytics = 'UA-11111111-1'

[params]
author = "kk-karl"
description = "é»‘å¤œç»™äº†æˆ‘é»‘è‰²çš„çœ¼ç›ï¼Œæˆ‘å´ç”¨å®ƒå¯»æ‰¾å…‰æ˜"
github = "kk-karl"
facebook = "kk-karl"
twitter = "kk-karl"
linkedin = "kk-karl"
instagram = "kk-karl"
tumblr = "kk-karl"
email = "zhaoyimin789@126.com"
url = "https://kk-karl.github.io/"
keywords = "blog,java,life, google analytics"
rss = true
lastmod = true
favicon = "/assets/favicon.ico"
avatar = "/images/avatar.png"
headerIcon = "/images/github-mark-white.png"
location = "China HeFei"
userStatusEmoji = "ğŸ˜€"
enableGitalk = true

[params.gitalk]
clientID = "Your client ID" # Your client ID
clientSecret = "Your client secret" # Your client secret
repo = "kk-karl.github.io" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
owner = "kk-karl" # æ‚¨çš„GitHub ID
admin = "kk-karl" # æ‚¨çš„GitHub ID
id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
perPage = 4 # Pagination size, with maximum 100.
pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
createIssueManually = false # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
distractionFreeMode = true # Enable hot key (cmd|ctrl + enter) submit comment.
proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
[[params.links]]
title = "Link"
href = "https://kk-karl.github.io"
[[params.links]]
title = "Link2"
href = "https://kk-karl.github.io"
icon = "/images/avatar.png"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
[services.googleAnalytics]
ID = "UA-123456-789"